ProyectoFinal/ProyectoFinal/Controllers/NegociosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using BussinesEntities;
using DAL;
using System.IO;

namespace ProyectoFinal.Controllers
{
    public class NegociosController : Controller
    {
        private SitcomEntities db = new SitcomEntities();
        private UsuarioEntity usuarioActual;
        private NegociosManager nm = new NegociosManager();
        private UsuariosManager um = new UsuariosManager();
        private DomicilioManager dm = new DomicilioManager();
        private NegocioEntity neg = new NegocioEntity();
        private DomicilioEntity dom = new DomicilioEntity();
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Nuevo() //PANTALLA CREAR NUEVO - NEGOCIOS
        {
            ObtenerUsuarioActual();
            if(usuarioActual.idPersona != null)
            {
                /*if (ValidarPermisoVista("Negocios", "Nuevo"))
                {*/
                ViewBag.Perfil = usuarioActual.idPerfil;
                ViewBag.TiposNegocio = new SelectList(db.TipoDeNegocio, "idTipoNegocio", "nombre");
                ViewBag.Rubros = new SelectList(db.Rubro, "idRubro", "nombreRubro");


                NegocioEntity neg = new NegocioEntity();//para tener un idNegocio=0 y no falle al llamar a la accion NuevoComercio.

                dom.listLocalidadesCercanas = dm.GetLocalidadesCercanas();
                SucursalEntity suc = new SucursalEntity()
                {
                    Domicilio = dom
                };
                neg.Sucursal.Add(suc);

                return View(neg);
            }
            else
            {
                return RedirectToAction("DatosPersonales", "Persona", new { returnUrl = "../Negocios/Nuevo" });
            }
            /*}
            else
                return RedirectToAction("ErrorPermisos", "Errores");*/
        }
        public ActionResult NuevoComercio(NegocioEntity negocio,
                                          [Bind(Include = "idRubro" )] ComercioEntity comercio,
                                          [Bind(Include = "localidadSeleccionada,barrio,calle,dpto,numero")] DomicilioEntity domEn,
                                          string telefono,
                                          HttpPostedFileBase imagenPrinc,
                                          HttpPostedFileBase imagenMuestra1,
                                          HttpPostedFileBase imagenMuestra2,
                                          HttpPostedFileBase imagenMuestra3,
                                          HttpPostedFileBase imagenMuestra4,
                                          HttpPostedFileBase imagenMuestra5,
                                          HttpPostedFileBase imagenMuestra6)
        {
            ObtenerUsuarioActual();

            neg.idUsuario = usuarioActual.idUsuario;
            neg.idTipoNegocio = 2;
            neg.nombre = negocio.nombre;
            neg.descripcion = negocio.descripcion;
            neg.Comercio = new List<ComercioEntity>() { comercio };

            neg.Sucursal.Add(new SucursalEntity()
            {
                esPrincipal = true,
                telefono = telefono,
                Domicilio = domEn
            });

            byte[] buffer = null;
            using (var binaryReader = new BinaryReader(imagenPrinc.InputStream))
            {
                buffer = binaryReader.ReadBytes(imagenPrinc.ContentLength);
            }

            FotosNegocio fotoPrinc = new FotosNegocio()
            {
                foto = buffer,
                esPrincipal = true
            };

            List<HttpPostedFileBase> listaHttp = new List<HttpPostedFileBase>() { imagenMuestra1, imagenMuestra2, imagenMuestra3, imagenMuestra4, imagenMuestra5, imagenMuestra6 };

            List<FotosNegocio> fotosNegocio = convertirImagenesMuestra(listaHttp);
            fotosNegocio.Add(fotoPrinc);

            neg.FotosNegocio = fotosNegocio;

            if (ModelState.IsValid)
            {
                if (nm.ValidarExisteNegocio(neg.nombre,null))
                    nm.AddNegocio(neg,usuarioActual);
                else
                {
                    ModelState.AddModelError("", "Un comercio con el mismo nombre ya está registrado. Por favor elige otro.");
                    ViewBag.Perfil = usuarioActual.idPerfil;
                    ViewBag.Rubros = new SelectList(db.Rubro, "idRubro", "nombreRubro", neg.Comercio.FirstOrDefault().idRubro);
                    ViewBag.TiposNegocio = new SelectList(db.TipoDeNegocio, "idTipoNegocio", "nombre", neg.idTipoNegocio);
                    return View("Nuevo", neg);
                }
            }

            return RedirectToAction("Index", "Home");
        }
        public ActionResult NuevoLugarHospedaje([Bind(Include = "nombre,descripcion")] NegocioEntity negocio,
                                                [Bind(Include = "localidadSeleccionada,barrio,calle,dpto,numero")] DomicilioEntity domEn,
                                           HttpPostedFileBase imagenPrinc,
                                           HttpPostedFileBase imagenMuestra1,
                                           HttpPostedFileBase imagenMuestra2,
                                           HttpPostedFileBase imagenMuestra3,
                                           HttpPostedFileBase imagenMuestra4,
                                           HttpPostedFileBase imagenMuestra5,
                                           HttpPostedFileBase imagenMuestra6,
                                           string telefono,
                                           int TipoHospedaje)
        {
            // PARTE NEGOCIO //
            ObtenerUsuarioActual();

            neg.idUsuario = usuarioActual.idUsuario;
            neg.idTipoNegocio = 1;
            neg.nombre = negocio.nombre;
            neg.descripcion = negocio.descripcion;
            neg.Sucursal.Add(new SucursalEntity()
            {
                esPrincipal = true,
                telefono = telefono,
                Domicilio = domEn
            });

            // FIN PARTE NEGOCIO //

            // PARTE IMAGENES //
            byte[] buffer = null;
            using (var binaryReader = new BinaryReader(imagenPrinc.InputStream))
            {
                buffer = binaryReader.ReadBytes(imagenPrinc.ContentLength);
            }

            FotosNegocio fotoPrinc = new FotosNegocio()
            {
                foto = buffer,
                esPrincipal = true
            };

            List<HttpPostedFileBase> listaHttp = new List<HttpPostedFileBase>() { imagenMuestra1, imagenMuestra2, imagenMuestra3, imagenMuestra4, imagenMuestra5, imagenMuestra6 };

            List<FotosNegocio> fotosNegocio = convertirImagenesMuestra(listaHttp);
            fotosNegocio.Add(fotoPrinc);

            neg.FotosNegocio = fotosNegocio;

            // FIN PARTE IMAGENES //

            // PARTE LUGAR HOSPEDAJE //
            LugarHospedajeEntity lug = new LugarHospedajeEntity();
            lug.idTipoLugarHospedaje = TipoHospedaje;
            lug.CaracteristicasHospedaje = new List<CaracteristicasHospedajeEntity>();
            neg.LugarHospedaje = new List<LugarHospedajeEntity>() { lug };

            SelectList carac = new SelectList(db.Caracteristica, "idCaracteristica", "nombre");
            foreach (var item in carac)
            {
                string s = Request.Form[item.Text];
                bool selected = false;

                if (s != "false" && s != null)
                    selected = true;

                if (selected)
                {
                    CaracteristicasHospedajeEntity c = new CaracteristicasHospedajeEntity()
                    {
                       idCaracteristica = int.Parse(item.Value)                            
                    };
                    neg.LugarHospedaje.FirstOrDefault().CaracteristicasHospedaje.Add(c);
                }
            }
                      

            switch (neg.LugarHospedaje.FirstOrDefault().idTipoLugarHospedaje)
            {
                case 1: List<CasaDptoOCabana> casaDptosOCabanas = new List<CasaDptoOCabana>() { new CasaDptoOCabana() };
                        neg.LugarHospedaje.FirstOrDefault().CasaDptoOCabana = casaDptosOCabanas;
                    break;

                case 2: List<ComplejoEntity> complejos = new List<ComplejoEntity>() { new ComplejoEntity() };
                        neg.LugarHospedaje.FirstOrDefault().Complejo = complejos;
                        neg.LugarHospedaje.FirstOrDefault().Complejo.FirstOrDefault().idCategoria = int.Parse(Request.Form["categ"].ToString());
                        neg.LugarHospedaje.FirstOrDefault().Complejo.FirstOrDefault().idTipoComplejo = int.Parse(Request.Form["tipos"].ToString());

                        int j = 0;
                        int capacidad;
                        int cantidad;
                        string idCapacidad = "Capacidad_" + j;
                        string idCantidad = "Cantidad_" + j;
                        int k = 1; //Para los nombres de las Casas/Dptos/Cabañas

                        List<CasaDptoOCabana> casasDptosOCabanas = new List<CasaDptoOCabana>();
                    
                        while(Request.Form[idCapacidad] != null && Request.Form[idCantidad] != null)
                        {
                            capacidad = int.Parse(Request.Form[idCapacidad]);
                            cantidad = int.Parse(Request.Form[idCantidad]);

                            for (int i = 0; i < cantidad; i++)
                            {
                                casasDptosOCabanas.Add(new CasaDptoOCabana()
                                    {
                                        nombreCasaDptoOCabana = "Alojamiento " + k,

ProyectoFinal/ProyectoFinal/Controllers/TramitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL;
using BussinesEntities;
using DAL;

namespace ProyectoFinal.Controllers
{
    public class TramitesController : Controller
    {
        //
        // GET: /Tramites/
        private UsuarioEntity usuarioActual;
        private UsuariosManager um = new UsuariosManager();
        private TramitesManager tm = new TramitesManager();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TramitesResp(int? id)
        {
            List<TramiteEntity> tramites = tm.GetAllTramites(id);

            foreach (var item in tramites)
            {
                if (item.idUsuarioResponsable == null)
                    item.Usuarios1 = new Usuarios() { nombreUsuario = "No Asignado" };
            }
            return View(tramites);
        }
        public ActionResult TomarTramiteResp(int id)
        {
            ObtenerUsuarioActual();
            TramiteEntity tra = tm.GetTramiteById(id);
            tm.CambiarEstadoTramite(tra, 2, usuarioActual);

            return RedirectToAction("TramitesResp");
        }
        public ActionResult CancelarTramite(int id, string returnUrl)
        {
            ObtenerUsuarioActual();
            TramiteEntity tra = tm.GetTramiteById(id);
            tm.CambiarEstadoTramite(tra, 5, usuarioActual);
            return RedirectToAction(returnUrl, new { mensaje = "¡Tu tramite fue cancelado!" });
        }
        public ActionResult TramitesUsuario(string mensaje)
        {
            ObtenerUsuarioActual();

            ViewBag.Perfil = usuarioActual.idPerfil;
            ViewBag.UsuarioActual = usuarioActual;
            ViewBag.Mensaje = mensaje;
            List<TramiteEntity> tramites = tm.GetTramitesByUsuario(usuarioActual);

            return View(tramites);
        }
        public ActionResult VerTramite(int id)
        {
            TramiteEntity tra = tm.GetTramiteById(id);

            switch (tra.idTipoTramite)
            {
                case 1: return RedirectToAction("EvalNegocio", "Negocios", new { id = tra.idNegocio, idTramite = tra.idTramite});
                case 2: return RedirectToAction("EvalSolicitudModulo", "Reservas", new { id = tra.idNegocio, idTramite = tra.idTramite });
                case 3: return RedirectToAction("EvalNegocio", "Negocios", new { id = tra.idNegocio, idTramite = tra.idTramite });
                default: return RedirectToAction("Index","Home");
           
            }
        }
        public ActionResult ResolverTramite(int idtramite, int accion, string comentario)
        {
            ObtenerUsuarioActual();
            TramiteEntity tra = tm.GetTramiteById(idtramite);
            tm.CambiarEstadoTramite(tra, accion, usuarioActual);

            return RedirectToAction("PanelControlUsuario", "Usuarios", new { mensaje = "Se resolvio el tramite correctamente!" });
        }
        public bool ValidarPermisoVista(string controlador, string vista) //METODO UNICO DEL CONTROLADOR PARA VALIDAR PERMISO DE LA VISTA (LLAMA AL MANEJADOR).
        {
            ObtenerUsuarioActual();
            return um.ValidarPermisoVista(usuarioActual, controlador, vista);
        }
        public void ObtenerUsuarioActual()
        {
            usuarioActual = (UsuarioEntity)Session["User"];
        }
	}
}

ProyectoFinal/ProyectoFinal/Views/Negocios/NegociosUsuario.cshtml
@model IEnumerable<DAL.Negocio>
@using GridMvc.Html

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Negocios del Usuario</title>
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- end: META -->
    <!-- start: MAIN CSS -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/assets/plugins/animate.css/animate.min.css">
    <!-- end: MAIN CSS -->
    <!-- start: CSS REQUIRED FOR SUBVIEW CONTENTS -->
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="~/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="~/assets/plugins/summernote/dist/summernote.css">
    <link rel="stylesheet" href="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="~/assets/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-select/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
    <link rel="stylesheet" href="~/assets/plugins/DataTables/media/css/DT_bootstrap.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
    <!-- end: CSS REQUIRED FOR THIS SUBVIEW CONTENTS-->
    <!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CORE CSS -->
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="stylesheet" href="~/assets/css/styles-responsive.css">
    <link rel="stylesheet" href="~/assets/css/plugins.css">
    <link rel="stylesheet" href="~/assets/css/themes/theme-default.css" type="text/css" id="skin_color">
    <link rel="stylesheet" href="~/assets/css/print.css" type="text/css" media="print" />
    <!-- end: CORE CSS -->

    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.custom.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>

    <script type="text/javascript">

        var perfil = "@ViewBag.Perfil"     
        var mensaje = "@ViewBag.Mensaje"

        $(document).ready(function(){


            if (perfil == 3) {
                $("#btnTusTramites").hide();
                $("#btnTusNegocios").hide();
                $("#btnTusTramitesAsignados").show();
            }
            else {
                $("#btnTusTramites").show();
                $("#btnTusNegocios").show();
                $("#btnTusTramitesAsignados").hide();
            }

            if(mensaje != ""){
                alert(mensaje);
            }

            $("#btnTusTramites").click(function () {
                window.location = '@Url.Action("TramitesUsuario","Tramites")';
            });

            $("#btnTusTramitesAsignados").click(function () {
                window.location = '@Url.Action("TramitesUsuario","Tramites")';
            });

            $("#btnModificarDatos").click(function () {
                window.location = '@Url.Action("EditUsuario","Usuarios")';
            });

            $("#btnTusNegocios").click(function () {
                window.location = '@Url.Action("NegociosUsuario","Negocios")';
            });
        });
          </script>

</head>
<body>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading">
                    
                    @{BussinesEntities.UsuarioEntity us = ViewBag.UsuarioActual;
                    <h4 class="panel-title">Usuario: <span class="text-bold">@us.nombreUsuario</span></h4>

                    <h4>@Html.DisplayFor(model => us.Perfiles.nombre)</h4>
                        
                    }

                </div>
                <div class="panel-body">
                    
                    <table cellspacing="3" cellpadding="3" class="tabla-principal" align="center">

                        <tr>
                            <td>
                                <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnModificarDatos">
                                    MODIFICÁ TUS DATOS
                                </button>
                                <br />

                            </td>
                            <td>
                                <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnTusNegocios">
                                    TUS NEGOCIOS
                                </button>
                                <br />

                            </td>
                            <td>
                                <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnTusTramites">
                                    TUS TRAMITES
                                </button>
                                <br />

                            </td>
                            <td>
                                <button class="btn btn-blue btn-lg" data-color="mint" data-style="expand-right" data-size="xl" id="btnTusTramitesAsignados">
                                    TUS TRAMITES ASIGNADOS
                                </button>
                            </td>
                        </tr>
                    </table>

                    <br />
                    <br />
                    @if (Model.Count() != 0)
                    {
                        @helper botonVer(DAL.Negocio n)
{
    if (n.idTipoNegocio == 1)
    {
        <button id="btnVerNegocio" onclick="window.location = '@Url.Action("VerHospedaje","Negocios",new { id = n.idNegocio })'" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="Ver"><i class="fa fa-search"></i></button>
    <button onclick="window.location = '@Url.Action("EditHospedaje","Negocios", new { idNegocio = n.idNegocio })'" class="btn btn-xs btn-blue tooltips" data-placement="top" data-original-title="Editar"><i class="fa fa-edit"></i></button>
    }
    else
    {
        <button id="btnVerNegocio" onclick="window.location = '@Url.Action("VerComercio","Negocios",new { id = n.idNegocio })'" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="Ver"><i class="fa fa-search"></i></button>
    <button onclick="window.location = '@Url.Action("EditComercio","Negocios", new { idNegocio = n.idNegocio })'" class="btn btn-xs btn-blue tooltips" data-placement="top" data-original-title="Editar"><i class="fa fa-edit"></i></button>
    }
}

        
                        @Html.Grid(Model).Columns(columns =>
        {
            //columns.Add(model => model.fechaAlta).Titled("Fecha Alta");
            columns.Add(model => model.nombre).Titled("Nombre").SetWidth(50);
            columns.Add(model => model.TipoDeNegocio.nombre).Titled("Tipo").SetWidth(50);
            columns.Add(model => model.idNegocio)
                .Titled("Acción")
                .Encoded(false)
                .Sanitized(false)
                .SetWidth(50)
                .RenderValueAs(n => botonVer(n));
        }).WithPaging(10).Sortable(true)


                    }
                    else
                    {

                        <div id="NoNegocios" style="align-self:center; font-size:20px; display:none">
                            <strong>
                                No tenés Negocios APROBADOS.
                            </strong>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
    <script src="~/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
    <!--<![endif]-->
    <script src="~/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/plugins/blockUI/jquery.blockUI.js"></script>
    <script src="~/assets/plugins/iCheck/jquery.icheck.min.js"></script>
    <script src="~/assets/plugins/moment/min/moment.min.js"></script>
    <script src="~/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
    <script src="~/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
    <script src="~/assets/plugins/bootbox/bootbox.min.js"></script>
    <script src="~/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
    <script src="~/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
    <script src="~/assets/plugins/jquery.appear/jquery.appear.js"></script>
    <script src="~/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
    <script src="~/assets/plugins/velocity/jquery.velocity.min.js"></script>
    <script src="~/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
    <!-- end: MAIN JAVASCRIPTS -->
    <!-- start: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
    <script src="~/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
    <script src="~/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
    <script src="~/assets/plugins/toastr/toastr.js"></script>
    <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
    <script src="~/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
    <script src="~/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
    <script src="~/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
    <script src="~/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
    <script src="~/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
    <script src="~/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/plugins/DataTables/media/js/DT_bootstrap.js"></script>
    <script src="~/assets/plugins/truncate/jquery.truncate.js"></script>
    <script src="~/assets/plugins/summernote/dist/summernote.min.js"></script>
    <script src="~/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script src="~/assets/js/subview.js"></script>
    <script src="~/assets/js/subview-examples.js"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR SUBVIEW CONTENTS -->
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <!-- start: CORE JAVASCRIPTS  -->
    <script src="~/assets/js/main.js"></script>
    <!-- end: CORE JAVASCRIPTS  -->
    <script>
        jQuery(document).ready(function () {
            Main.init();
            SVExamples.init();
        });
    </script>


 
</body>



</html>

ProyectoFinal/ProyectoFinal/Views/Negocios/NuevoCom.cshtml
@model BussinesEntities.NegocioEntity
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title></title>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.custom.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>

<body>
    @using (Html.BeginForm("NuevoComercio", "Negocios", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
             <div class="form-group">
                    @Html.Label("Nombre del COMERCIO:", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre)
                        @Html.ValidationMessageFor(model => model.nombre)
                    </div>
              </div>
            
                <div class="form-group">
                    @Html.Label("Rubro: ", new { @class = "control-label col-md-2", id = "lblRubro" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Comercio.FirstOrDefault().idRubro, (SelectList)ViewBag.Rubros, "-- SELECCIONA EL RUBRO --", new { id = "ddlRubros" })
                        @Html.ValidationMessageFor(model => model.Comercio.FirstOrDefault().idRubro)
                    </div>
                </div>

        <div class="form-group">
            @Html.Label("Descripcion:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.descripcion, new { @class = "descripcionNegocio" })
                @Html.ValidationMessageFor(model => model.descripcion)
            </div>
        </div>
    <br />
        <div class="form-group">
            @Html.Label("Imagen Principal:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="imagenPrinc" id="imagenPrinc" />
            </div>
        </div>
    <br />
        <div class="form-group">
            @Html.Label("Imágebes del Negocio:", new { @class = "control-label col-md-2" })
            
            <table>
                <tr>
                    <td><input type="file" name="imagenMuestra1" id="imagenMuestra1" /></td>
                    <td><input type="file" name="imagenMuestra2" id="imagenMuestra2" /></td>
                    <td><input type="file" name="imagenMuestra3" id="imagenMuestra3" /></td>
                </tr>
                <tr>
                    <td><input type="file" name="imagenMuestra4" id="imagenMuestra4" /></td>
                    <td><input type="file" name="imagenMuestra5" id="imagenMuestra5" /></td>
                    <td><input type="file" name="imagenMuestra6" id="imagenMuestra6" /></td>
                </tr>
            </table>
           
        </div>
    <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="REGISTRAR COMERCIO" class="btn btn-default" />
            </div>
        </div>
        @ViewBag.Error
        }
 </body>

</html>

ProyectoFinal/ProyectoFinal/Views/Negocios/VerNegocio.cshtml
@model BussinesEntities.NegocioEntity
@{
    ViewBag.Title = "VerNegocio";
}

<h2>VerNegocio</h2>